Trying urllib3 ... ok
Trying requests ... ok
Trying python-dateutil ... ok
Trying idna ... ok
Trying rsa ... ok
Trying attrs ... ok
Trying wcwidth ... ok
Trying pyrsistent ... ok
Trying configparser ... ok
Trying pexpect ... ok
Trying docker ... ok
Trying tqdm ... ok
Trying tabulate ... ok
Trying webencodings ... ok
Trying pymongo ... ok
Trying pathlib2 ... ok
Trying flake8 ... ok
Trying bleach ... ok
Trying pyzmq ... timedout
Trying pylint ... ok
Trying pytest-cov ... ok
Trying yarl ... ok
Trying xmltodict ... ok
Trying ruamel-yaml ... ok
Trying tzlocal ... ok
Trying html5lib ... ok
Trying websockets ... ok
Trying google-cloud-pubsub ... ok
Trying singledispatch ... ok
Trying text-unidecode ... ok
Trying snowflake-connector-python ... ok
Trying celery ... ok
Trying shapely ... failed
Output:     ERROR: Command errored out with exit status 1:
     command: /home/inada-n/pypi-ansi/.venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-hrews0fb/shapely/setup.py'"'"'; __file__='"'"'/tmp/pip-install-hrews0fb/shapely/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-hrews0fb/shapely/
    Complete output (11 lines):
    Failed `CDLL(libgeos_c.so.1)`
    Failed `CDLL(libgeos_c.so)`
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-hrews0fb/shapely/setup.py", line 85, in <module>
        from shapely._buildcfg import geos_version_string, geos_version, \
      File "/tmp/pip-install-hrews0fb/shapely/shapely/_buildcfg.py", line 169, in <module>
        lgeos = load_dll('geos_c',
      File "/tmp/pip-install-hrews0fb/shapely/shapely/_buildcfg.py", line 162, in load_dll
        raise OSError(
    OSError: Could not find library geos_c or load any of its variants ['libgeos_c.so.1', 'libgeos_c.so']
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


Trying arrow ... ok
Trying slackclient ... ok
Trying smart-open ... ok
Trying pipenv ... timedout
Trying et-xmlfile ... ok
Trying unicodecsv ... ok
Trying faker ... ok
Trying service-identity ... ok
Trying black ... ok
Trying python-dotenv ... ok
Trying python-daemon ... timedout
Trying geopy ... ok
Trying azure-mgmt-sql ... ok
Trying python-levenshtein ... ok
Trying idna-ssl ... ok
Trying pyproj ... timedout
Trying geoip2 ... ok
Trying aws-xray-sdk ... ok
Trying azure-mgmt-eventgrid ... ok
Trying pycairo ... failed
Output:     ERROR: Command errored out with exit status 1:
     command: /home/inada-n/pypi-ansi/.venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-sn8a02wj/pycairo/setup.py'"'"'; __file__='"'"'/tmp/pip-install-sn8a02wj/pycairo/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-xjyy47nm/install-record.txt --single-version-externally-managed --compile --install-headers /home/inada-n/pypi-ansi/.venv/include/site/python3.8/pycairo
         cwd: /tmp/pip-install-sn8a02wj/pycairo/
    Complete output (15 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.8
    creating build/lib.linux-x86_64-3.8/cairo
    copying cairo/__init__.py -> build/lib.linux-x86_64-3.8/cairo
    copying cairo/__init__.pyi -> build/lib.linux-x86_64-3.8/cairo
    copying cairo/py.typed -> build/lib.linux-x86_64-3.8/cairo
    running build_ext
    Package cairo was not found in the pkg-config search path.
    Perhaps you should add the directory containing `cairo.pc'
    to the PKG_CONFIG_PATH environment variable
    Package 'cairo', required by 'virtual:world', not found
    Command '['pkg-config', '--print-errors', '--exists', 'cairo >= 1.13.1']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/inada-n/pypi-ansi/.venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-sn8a02wj/pycairo/setup.py'"'"'; __file__='"'"'/tmp/pip-install-sn8a02wj/pycairo/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-xjyy47nm/install-record.txt --single-version-externally-managed --compile --install-headers /home/inada-n/pypi-ansi/.venv/include/site/python3.8/pycairo Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


Trying holidays ... ok
Trying thinc ... timedout
Trying pydocumentdb ... failed
Output:     ERROR: Command errored out with exit status 1:
     command: /home/inada-n/pypi-ansi/.venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-h9uy3v9j/pydocumentdb/setup.py'"'"'; __file__='"'"'/tmp/pip-install-h9uy3v9j/pydocumentdb/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-h9uy3v9j/pydocumentdb/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-h9uy3v9j/pydocumentdb/setup.py", line 10, in <module>
        with open("changelog.md", encoding="utf-8") as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'changelog.md'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


Trying spacy ... timedout
Trying humanfriendly ... ok
Trying factory-boy ... ok
Trying watchdog ... ok
Trying hiredis ... ok
Trying azure-mgmt-datafactory ... ok
Trying cymem ... ok
Trying aws-sam-translator ... ok
Trying phonenumbers ... ok
Trying blis ... timedout
Trying srsly ... failed
Output:     ERROR: Command errored out with exit status 1:
     command: /home/inada-n/pypi-ansi/.venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ltoazu_g/srsly/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ltoazu_g/srsly/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-ltoazu_g/srsly/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ltoazu_g/srsly/setup.py", line 7, in <module>
        from Cython.Build import cythonize
    ModuleNotFoundError: No module named 'Cython'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


Trying supervisor ... ok
Trying django-debug-toolbar ... ok
Trying pypandoc ... ok
Trying wasabi ... ok
Trying progressbar2 ... ok
Trying poyo ... ok
Trying pyaml ... ok
Trying tftpy ... ok
Trying dateparser ... ok
Trying structlog ... ok
Trying pytest-timeout ... ok
Trying humanize ... ok
Trying pycountry ... ok
Trying cheroot ... timedout
Trying fiona ... failed
Output:     ERROR: Command errored out with exit status 1:
     command: /home/inada-n/pypi-ansi/.venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-9oeyy8os/fiona/setup.py'"'"'; __file__='"'"'/tmp/pip-install-9oeyy8os/fiona/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-9oeyy8os/fiona/
    Complete output (2 lines):
    Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'
    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


Trying rfc3986 ... ok
Trying weasyprint ... ok
Trying bumpversion ... ok
Trying catalogue ... ok
Trying portend ... timedout
Trying pycares ... timedout
Trying parameterized ... ok
Trying poetry ... failed
Output:   ERROR: Command errored out with exit status 1:
   command: /home/inada-n/pypi-ansi/.venv/bin/python3 /home/inada-n/pypi-ansi/.venv/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp2wdgkjie
       cwd: /tmp/pip-install-zmx5sp_o/poetry
  Complete output (36 lines):
  Traceback (most recent call last):
    File "/home/inada-n/pypi-ansi/.venv/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>
      main()
    File "/home/inada-n/pypi-ansi/.venv/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 197, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/inada-n/pypi-ansi/.venv/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 54, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-3iqfwish/overlay/lib/python3.8/site-packages/intreehooks.py", line 53, in get_requires_for_build_wheel
      return self._backend.get_requires_for_build_sdist(config_settings)
    File "/tmp/pip-build-env-3iqfwish/overlay/lib/python3.8/site-packages/intreehooks.py", line 38, in _backend
      obj = self._module_from_dir(modname)
    File "/tmp/pip-build-env-3iqfwish/overlay/lib/python3.8/site-packages/intreehooks.py", line 25, in _module_from_dir
      mod = importlib.import_module(modname)
    File "/home/inada-n/pyenv/versions/3.8.1/lib/python3.8/importlib/__init__.py", line 127, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
    File "<frozen importlib._bootstrap>", line 991, in _find_and_load
    File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
    File "<frozen importlib._bootstrap>", line 991, in _find_and_load
    File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 783, in exec_module
    File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    File "/tmp/pip-install-zmx5sp_o/poetry/poetry/masonry/__init__.py", line 10, in <module>
      from .builder import Builder
    File "/tmp/pip-install-zmx5sp_o/poetry/poetry/masonry/builder.py", line 1, in <module>
      from .builders.complete import CompleteBuilder
    File "/tmp/pip-install-zmx5sp_o/poetry/poetry/masonry/builders/__init__.py", line 1, in <module>
      from .complete import CompleteBuilder
    File "/tmp/pip-install-zmx5sp_o/poetry/poetry/masonry/builders/complete.py", line 6, in <module>
      from poetry.factory import Factory
    File "/tmp/pip-install-zmx5sp_o/poetry/poetry/factory.py", line 10, in <module>
      from clikit.api.io.io import IO
  ModuleNotFoundError: No module named 'clikit'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /home/inada-n/pypi-ansi/.venv/bin/python3 /home/inada-n/pypi-ansi/.venv/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp2wdgkjie Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


Trying objectpath ... ok
Trying ruamel-ordereddict ... failed
Output:     ERROR: Command errored out with exit status 1:
     command: /home/inada-n/pypi-ansi/.venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ghf1br_n/ruamel-ordereddict/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ghf1br_n/ruamel-ordereddict/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-m93lq7ag/install-record.txt --single-version-externally-managed --compile --install-headers /home/inada-n/pypi-ansi/.venv/include/site/python3.8/ruamel-ordereddict
         cwd: /tmp/pip-install-ghf1br_n/ruamel-ordereddict/
    Complete output (64 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.8
    creating build/lib.linux-x86_64-3.8/ruamel
    creating build/lib.linux-x86_64-3.8/ruamel/ordereddict
    copying ./__init__.py -> build/lib.linux-x86_64-3.8/ruamel/ordereddict
    running build_ext
    building '_ordereddict' extension
    creating build/temp.linux-x86_64-3.8
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/home/inada-n/pypi-ansi/.venv/include -I/home/inada-n/pyenv/versions/3.8.1/include/python3.8 -c ordereddict.c -o build/temp.linux-x86_64-3.8/ordereddict.o
    ordereddict.c: In function 'PyOrderedDict_GetItem':
    ordereddict.c:973:30: warning: implicit declaration of function '_Py_atomic_load_relaxed' [-Wimplicit-function-declaration]
      973 |     tstate = (PyThreadState*)_Py_atomic_load_relaxed(
          |                              ^~~~~~~~~~~~~~~~~~~~~~~
    ordereddict.c:974:10: error: '_PyThreadState_Current' undeclared (first use in this function); did you mean 'PyThreadState_Next'?
      974 |         &_PyThreadState_Current);
          |          ^~~~~~~~~~~~~~~~~~~~~~
          |          PyThreadState_Next
    ordereddict.c:974:10: note: each undeclared identifier is reported only once for each function it appears in
    ordereddict.c: In function 'dict_subscript':
    ordereddict.c:1580:47: warning: passing argument 2 of '_PyObject_LookupSpecial' from incompatible pointer type [-Wincompatible-pointer-types]
     1580 |                                               "__missing__",
          |                                               ^~~~~~~~~~~~~
          |                                               |
          |                                               char *
    In file included from /home/inada-n/pyenv/versions/3.8.1/include/python3.8/object.h:746,
                     from /home/inada-n/pyenv/versions/3.8.1/include/python3.8/pytime.h:6,
                     from /home/inada-n/pyenv/versions/3.8.1/include/python3.8/Python.h:85,
                     from ordereddict.c:22:
    /home/inada-n/pyenv/versions/3.8.1/include/python3.8/cpython/object.h:298:24: note: expected '_Py_Identifier *' {aka 'struct _Py_Identifier *'} but argument is of type 'char *'
      298 | PyAPI_FUNC(PyObject *) _PyObject_LookupSpecial(PyObject *, _Py_Identifier *);
          |                        ^~~~~~~~~~~~~~~~~~~~~~~
    ordereddict.c:1579:23: error: too many arguments to function '_PyObject_LookupSpecial'
     1579 |             missing = _PyObject_LookupSpecial((PyObject *)mp,
          |                       ^~~~~~~~~~~~~~~~~~~~~~~
    In file included from /home/inada-n/pyenv/versions/3.8.1/include/python3.8/object.h:746,
                     from /home/inada-n/pyenv/versions/3.8.1/include/python3.8/pytime.h:6,
                     from /home/inada-n/pyenv/versions/3.8.1/include/python3.8/Python.h:85,
                     from ordereddict.c:22:
    /home/inada-n/pyenv/versions/3.8.1/include/python3.8/cpython/object.h:298:24: note: declared here
      298 | PyAPI_FUNC(PyObject *) _PyObject_LookupSpecial(PyObject *, _Py_Identifier *);
          |                        ^~~~~~~~~~~~~~~~~~~~~~~
    ordereddict.c: In function 'dict_ass_slice':
    ordereddict.c:1650:15: warning: comparison of integer expressions of different signedness: 'Py_ssize_t' {aka 'long int'} and 'long unsigned int' [-Wsign-compare]
     1650 |         if (s > sizeof(recycle_on_stack)) {
          |               ^
    ordereddict.c: In function 'dict_sizeof':
    ordereddict.c:2858:11: error: 'PyDictObject' {aka 'struct <anonymous>'} has no member named 'ma_table'
     2858 |     if (mp->ma_table != mp->ma_smalltable)
          |           ^~
    ordereddict.c:2858:27: error: 'PyDictObject' {aka 'struct <anonymous>'} has no member named 'ma_smalltable'
     2858 |     if (mp->ma_table != mp->ma_smalltable)
          |                           ^~
    ordereddict.c:2859:24: error: 'PyDictObject' {aka 'struct <anonymous>'} has no member named 'ma_mask'
     2859 |         res = res + (mp->ma_mask + 1) * sizeof(PyOrderedDictEntry);
          |                        ^~
    ordereddict.c: In function 'dict_new':
    ordereddict.c:3520:13: warning: implicit declaration of function '_PyObject_GC_UNTRACK'; did you mean 'PyObject_GC_UnTrack'? [-Wimplicit-function-declaration]
     3520 |             _PyObject_GC_UNTRACK(d);
          |             ^~~~~~~~~~~~~~~~~~~~
          |             PyObject_GC_UnTrack
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/inada-n/pypi-ansi/.venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ghf1br_n/ruamel-ordereddict/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ghf1br_n/ruamel-ordereddict/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-m93lq7ag/install-record.txt --single-version-externally-managed --compile --install-headers /home/inada-n/pypi-ansi/.venv/include/site/python3.8/ruamel-ordereddict Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


Trying coloredlogs ... ok
Trying koalas ... ok
Trying certbot ... ok
Trying fonttools ... ok
Trying aiodns ... ok
Trying validators ... ok
Trying graphene ... ok
Trying deprecation ... ok
Trying paho-mqtt ... ok
Trying ntlm-auth ... ok
Trying theano ... ok
Trying terminaltables ... ok
Trying pint ... ok
Trying qrcode ... ok
Trying docker-py ... ok
Trying sshtunnel ... ok
Trying workalendar ... ok
Trying mongoengine ... ok
Trying pygtrie ... ok
Trying imbalanced-learn ... ok
Trying emoji ... ok
Trying jplephem ... ok
Trying sgp4 ... ok
Trying skyfield ... ok
Trying serpent ... ok
Trying async-generator ... ok
Trying ciso8601 ... ok
Trying drf-yasg ... timedout
Trying wandb ... ok
Trying vcrpy ... ok
Trying falcon ... ok
Trying wikipedia ... ok
Trying pyinstaller ... ok
Trying pyinotify ... ok
Trying sentencepiece ... failed
Output:     ERROR: Command errored out with exit status 1:
     command: /home/inada-n/pypi-ansi/.venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-5usvx204/sentencepiece/setup.py'"'"'; __file__='"'"'/tmp/pip-install-5usvx204/sentencepiece/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-5usvx204/sentencepiece/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-5usvx204/sentencepiece/setup.py", line 29, in <module>
        with codecs.open(os.path.join('..', 'VERSION'), 'r', 'utf-8') as f:
      File "/home/inada-n/pyenv/versions/3.8.1/lib/python3.8/codecs.py", line 905, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: '../VERSION'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


Trying azure-cli-core ... ok
Trying schema ... ok
Trying hpack ... ok
Trying warlock ... ok
Trying h2 ... ok
Trying pytest-sugar ... ok
Trying rjsmin ... ok
Trying azureml-dataprep ... failed
Output:   ERROR: Could not find a version that satisfies the requirement azureml-dataprep (from versions: none)
ERROR: No matching distribution found for azureml-dataprep
WARNING: You are using pip version 19.2.3, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


Trying flake8-bugbear ... ok
Trying argon2-cffi ... timedout
Trying django-multiselectfield ... ok
Trying selectors34 ... ok
Trying httpretty ... ok
Trying wptools ... ok
Trying google-cloud-automl ... ok
Trying diskcache ... ok
Trying safety ... ok
Trying ftfy ... ok
Trying django-countries ... ok
Trying hashids ... ok
Trying pdf2image ... ok
Trying uvicorn ... ok
Trying xxhash ... ok
Trying rfc3987 ... ok
Trying polib ... ok
Trying azure-cli ... ok
Trying google-cloud-bigquery-storage ... ok
Trying humpty ... ok
Trying python-stdnum ... ok
Trying awsebcli ... ok
Trying bidict ... timedout
Trying jws ... ok
Trying instana ... ok
Trying rcssmin ... ok
Trying dulwich ... ok
Trying intervaltree ... ok
Trying javaproperties ... ok
Trying phonenumberslite ... ok
Trying signalfx ... failed
Output:   ERROR: Could not find a version that satisfies the requirement signalfx (from versions: none)
ERROR: No matching distribution found for signalfx
WARNING: You are using pip version 19.2.3, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


Trying email-validator ... ok
Trying pyod ... ok
Trying google-cloud-iam ... ok
Trying ec2-metadata ... ok
Trying pytest-benchmark ... ok
Trying google-cloud-scheduler ... ok
Trying aws-sam-cli ... ok
Trying orjson ... timedout
Trying google-cloud-talent ... ok
Trying google-cloud-datacatalog ... ok
Trying google-cloud-datalabeling ... ok
Trying google-cloud-webrisk ... ok
Trying dash ... ok
Trying starlette ... ok
Trying parsimonious ... ok
Trying smmap ... ok
Trying icalendar ... ok
Trying pytest-flask ... ok
Trying publicsuffix ... ok
Trying ephem ... timedout
Trying tree-format ... ok
Trying loguru ... ok
Trying pytest-watch ... ok
Trying pyreadline ... ok
Trying liac-arff ... ok
Trying transitions ... ok
Trying transformers ... ok
Trying pdbpp ... ok
Trying django-treebeard ... ok
Trying objgraph ... failed
Output:     ERROR: Command errored out with exit status 1:
     command: /home/inada-n/pypi-ansi/.venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-hxc1gft_/objgraph/setup.py'"'"'; __file__='"'"'/tmp/pip-install-hxc1gft_/objgraph/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-hxc1gft_/objgraph/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-hxc1gft_/objgraph/setup.py", line 2, in <module>
        import doctest
      File "/home/inada-n/pyenv/versions/3.8.1/lib/python3.8/doctest.py", line 100, in <module>
        import pdb
      File "/home/inada-n/pypi-ansi/.venv/lib/python3.8/site-packages/_pdbpp_path_hack/pdb.py", line 5, in <module>
        exec(compile(f.read(), pdb_path, 'exec'))
      File "/home/inada-n/pypi-ansi/.venv/lib/python3.8/site-packages/pdb.py", line 23, in <module>
        from fancycompleter import Completer, ConfigurableClass, Color
    ModuleNotFoundError: No module named 'fancycompleter'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


Trying wasmer ... failed
Output:   ERROR: Could not find a version that satisfies the requirement wasmer (from versions: none)
ERROR: No matching distribution found for wasmer
WARNING: You are using pip version 19.2.3, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


Trying routes ... ok
Trying first ... ok
Trying latexcodec ... ok
Trying elastic-apm ... timedout
Trying requests-pkcs12 ... ok
Trying pyshp ... ok
Trying jieba ... ok
Trying boxsdk ... ok
Trying gremlinpython ... ok
Trying mecab-python3 ... failed
Output:     ERROR: Command errored out with exit status 1:
     command: /home/inada-n/pypi-ansi/.venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-c7plk3aq/mecab-python3/setup.py'"'"'; __file__='"'"'/tmp/pip-install-c7plk3aq/mecab-python3/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-apez32by/install-record.txt --single-version-externally-managed --compile --install-headers /home/inada-n/pypi-ansi/.venv/include/site/python3.8/mecab-python3
         cwd: /tmp/pip-install-c7plk3aq/mecab-python3/
    Complete output (9 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.8
    creating build/lib.linux-x86_64-3.8/MeCab
    copying src/MeCab/__init__.py -> build/lib.linux-x86_64-3.8/MeCab
    running build_ext
    error: [Errno 2] No such file or directory: 'mecab-config'
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/inada-n/pypi-ansi/.venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-c7plk3aq/mecab-python3/setup.py'"'"'; __file__='"'"'/tmp/pip-install-c7plk3aq/mecab-python3/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-apez32by/install-record.txt --single-version-externally-managed --compile --install-headers /home/inada-n/pypi-ansi/.venv/include/site/python3.8/mecab-python3 Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


Trying aiohttp-cors ... ok
Trying combo ... ok
Trying zeroconf ... ok
Trying fasttext ... timedout
Trying ffmpeg-quality-metrics ... ok
Trying fastapi ... timedout
Trying recordclass ... ok
Trying tensorflow-probability ... ok
Trying pyahocorasick ... ok
Trying trains ... failed
Output:   ERROR: Could not find a version that satisfies the requirement trains (from versions: none)
ERROR: No matching distribution found for trains
WARNING: You are using pip version 19.2.3, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


Trying ncclient ... ok
Trying verboselogs ... ok
Trying googletrans ... ok
Trying easy-thumbnails ... ok
Trying eth-typing ... ok
Trying django-heroku ... ok
Trying dynaconf ... ok
Trying tinydb ... ok
Trying scikit-surprise ... timedout
Trying oss2 ... ok
Trying nteract-scrapbook ... ok
Trying web3 ... ok
Trying python-rapidjson ... timedout
Trying sphinx-autodoc-typehints ... timedout
Trying stestr ... ok
Trying fastcluster ... timedout
Trying pygeohash ... ok
Trying annoy ... timedout
Trying httpie ... ok
Trying cron-descriptor ... ok
Trying xmlschema ... ok
Trying django-pipeline ... ok
Trying records ... ok
Trying py-spy ... failed
Output:   ERROR: Could not find a version that satisfies the requirement py-spy (from versions: none)
ERROR: No matching distribution found for py-spy
WARNING: You are using pip version 19.2.3, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


Trying filetype ... ok
Trying pytest-mypy ... timedout
Trying mahotas ... failed
Output:     ERROR: Command errored out with exit status 1:
     command: /home/inada-n/pypi-ansi/.venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-3g99mel1/mahotas/setup.py'"'"'; __file__='"'"'/tmp/pip-install-3g99mel1/mahotas/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-_zgrddju/install-record.txt --single-version-externally-managed --compile --install-headers /home/inada-n/pypi-ansi/.venv/include/site/python3.8/mahotas
         cwd: /tmp/pip-install-3g99mel1/mahotas/
    Complete output (132 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.8
    creating build/lib.linux-x86_64-3.8/mahotas
    copying mahotas/center_of_mass.py -> build/lib.linux-x86_64-3.8/mahotas
    copying mahotas/histogram.py -> build/lib.linux-x86_64-3.8/mahotas
    copying mahotas/surf.py -> build/lib.linux-x86_64-3.8/mahotas
    copying mahotas/features_cli.py -> build/lib.linux-x86_64-3.8/mahotas
    copying mahotas/_filters.py -> build/lib.linux-x86_64-3.8/mahotas
    copying mahotas/bbox.py -> build/lib.linux-x86_64-3.8/mahotas
    copying mahotas/moments.py -> build/lib.linux-x86_64-3.8/mahotas
    copying mahotas/edge.py -> build/lib.linux-x86_64-3.8/mahotas
    copying mahotas/__init__.py -> build/lib.linux-x86_64-3.8/mahotas
    copying mahotas/tas.py -> build/lib.linux-x86_64-3.8/mahotas
    copying mahotas/texture.py -> build/lib.linux-x86_64-3.8/mahotas
    copying mahotas/lbp.py -> build/lib.linux-x86_64-3.8/mahotas
    copying mahotas/bwperim.py -> build/lib.linux-x86_64-3.8/mahotas
    copying mahotas/morph.py -> build/lib.linux-x86_64-3.8/mahotas
    copying mahotas/thresholding.py -> build/lib.linux-x86_64-3.8/mahotas
    copying mahotas/colors.py -> build/lib.linux-x86_64-3.8/mahotas
    copying mahotas/distance.py -> build/lib.linux-x86_64-3.8/mahotas
    copying mahotas/resize.py -> build/lib.linux-x86_64-3.8/mahotas
    copying mahotas/interpolate.py -> build/lib.linux-x86_64-3.8/mahotas
    copying mahotas/mahotas_version.py -> build/lib.linux-x86_64-3.8/mahotas
    copying mahotas/thin.py -> build/lib.linux-x86_64-3.8/mahotas
    copying mahotas/segmentation.py -> build/lib.linux-x86_64-3.8/mahotas
    copying mahotas/polygon.py -> build/lib.linux-x86_64-3.8/mahotas
    copying mahotas/convolve.py -> build/lib.linux-x86_64-3.8/mahotas
    copying mahotas/internal.py -> build/lib.linux-x86_64-3.8/mahotas
    copying mahotas/labeled.py -> build/lib.linux-x86_64-3.8/mahotas
    copying mahotas/stretch.py -> build/lib.linux-x86_64-3.8/mahotas
    copying mahotas/freeimage.py -> build/lib.linux-x86_64-3.8/mahotas
    copying mahotas/zernike.py -> build/lib.linux-x86_64-3.8/mahotas
    copying mahotas/euler.py -> build/lib.linux-x86_64-3.8/mahotas
    creating build/lib.linux-x86_64-3.8/mahotas/io
    copying mahotas/io/__init__.py -> build/lib.linux-x86_64-3.8/mahotas/io
    copying mahotas/io/pil.py -> build/lib.linux-x86_64-3.8/mahotas/io
    copying mahotas/io/freeimage.py -> build/lib.linux-x86_64-3.8/mahotas/io
    creating build/lib.linux-x86_64-3.8/mahotas/features
    copying mahotas/features/surf.py -> build/lib.linux-x86_64-3.8/mahotas/features
    copying mahotas/features/moments.py -> build/lib.linux-x86_64-3.8/mahotas/features
    copying mahotas/features/__init__.py -> build/lib.linux-x86_64-3.8/mahotas/features
    copying mahotas/features/tas.py -> build/lib.linux-x86_64-3.8/mahotas/features
    copying mahotas/features/texture.py -> build/lib.linux-x86_64-3.8/mahotas/features
    copying mahotas/features/lbp.py -> build/lib.linux-x86_64-3.8/mahotas/features
    copying mahotas/features/shape.py -> build/lib.linux-x86_64-3.8/mahotas/features
    copying mahotas/features/zernike.py -> build/lib.linux-x86_64-3.8/mahotas/features
    creating build/lib.linux-x86_64-3.8/mahotas/demos
    copying mahotas/demos/wavelet_compress.py -> build/lib.linux-x86_64-3.8/mahotas/demos
    copying mahotas/demos/surf_luispedro.py -> build/lib.linux-x86_64-3.8/mahotas/demos
    copying mahotas/demos/edge_demo.py -> build/lib.linux-x86_64-3.8/mahotas/demos
    copying mahotas/demos/wally.py -> build/lib.linux-x86_64-3.8/mahotas/demos
    copying mahotas/demos/__init__.py -> build/lib.linux-x86_64-3.8/mahotas/demos
    copying mahotas/demos/surf_gaussians.py -> build/lib.linux-x86_64-3.8/mahotas/demos
    copying mahotas/demos/thresholding.py -> build/lib.linux-x86_64-3.8/mahotas/demos
    copying mahotas/demos/distance.py -> build/lib.linux-x86_64-3.8/mahotas/demos
    copying mahotas/demos/morphology.py -> build/lib.linux-x86_64-3.8/mahotas/demos
    copying mahotas/demos/nuclear.py -> build/lib.linux-x86_64-3.8/mahotas/demos
    copying mahotas/demos/superpixels.py -> build/lib.linux-x86_64-3.8/mahotas/demos
    copying mahotas/demos/nuclear_distance_watershed.py -> build/lib.linux-x86_64-3.8/mahotas/demos
    creating build/lib.linux-x86_64-3.8/mahotas/tests
    copying mahotas/tests/test_label.py -> build/lib.linux-x86_64-3.8/mahotas/tests
    copying mahotas/tests/test_io.py -> build/lib.linux-x86_64-3.8/mahotas/tests
    copying mahotas/tests/test_stretch.py -> build/lib.linux-x86_64-3.8/mahotas/tests
    copying mahotas/tests/test_thresholding.py -> build/lib.linux-x86_64-3.8/mahotas/tests
    copying mahotas/tests/test_distance.py -> build/lib.linux-x86_64-3.8/mahotas/tests
    copying mahotas/tests/test_mahotas.py -> build/lib.linux-x86_64-3.8/mahotas/tests
    copying mahotas/tests/test_watershed.py -> build/lib.linux-x86_64-3.8/mahotas/tests
    copying mahotas/tests/test_morph.py -> build/lib.linux-x86_64-3.8/mahotas/tests
    copying mahotas/tests/__init__.py -> build/lib.linux-x86_64-3.8/mahotas/tests
    copying mahotas/tests/test_interpolate.py -> build/lib.linux-x86_64-3.8/mahotas/tests
    copying mahotas/tests/test_surf.py -> build/lib.linux-x86_64-3.8/mahotas/tests
    copying mahotas/tests/test_majority.py -> build/lib.linux-x86_64-3.8/mahotas/tests
    copying mahotas/tests/test_freeimage.py -> build/lib.linux-x86_64-3.8/mahotas/tests
    copying mahotas/tests/test_citation.py -> build/lib.linux-x86_64-3.8/mahotas/tests
    copying mahotas/tests/test_internal.py -> build/lib.linux-x86_64-3.8/mahotas/tests
    copying mahotas/tests/test_bbox.py -> build/lib.linux-x86_64-3.8/mahotas/tests
    copying mahotas/tests/test_zernike.py -> build/lib.linux-x86_64-3.8/mahotas/tests
    copying mahotas/tests/test_thin.py -> build/lib.linux-x86_64-3.8/mahotas/tests
    copying mahotas/tests/test_surf_regression.py -> build/lib.linux-x86_64-3.8/mahotas/tests
    copying mahotas/tests/pymorph_copy.py -> build/lib.linux-x86_64-3.8/mahotas/tests
    copying mahotas/tests/test_hitmiss.py -> build/lib.linux-x86_64-3.8/mahotas/tests
    copying mahotas/tests/test_segmentation.py -> build/lib.linux-x86_64-3.8/mahotas/tests
    copying mahotas/tests/test_histogram.py -> build/lib.linux-x86_64-3.8/mahotas/tests
    copying mahotas/tests/test_filters.py -> build/lib.linux-x86_64-3.8/mahotas/tests
    copying mahotas/tests/test_colors.py -> build/lib.linux-x86_64-3.8/mahotas/tests
    copying mahotas/tests/test_demos.py -> build/lib.linux-x86_64-3.8/mahotas/tests
    copying mahotas/tests/test_features_shape.py -> build/lib.linux-x86_64-3.8/mahotas/tests
    copying mahotas/tests/test_close_holes.py -> build/lib.linux-x86_64-3.8/mahotas/tests
    copying mahotas/tests/test_texture.py -> build/lib.linux-x86_64-3.8/mahotas/tests
    copying mahotas/tests/test_imresize.py -> build/lib.linux-x86_64-3.8/mahotas/tests
    copying mahotas/tests/test_euler.py -> build/lib.linux-x86_64-3.8/mahotas/tests
    copying mahotas/tests/test_bwperim.py -> build/lib.linux-x86_64-3.8/mahotas/tests
    copying mahotas/tests/test_lbp.py -> build/lib.linux-x86_64-3.8/mahotas/tests
    copying mahotas/tests/test_tas.py -> build/lib.linux-x86_64-3.8/mahotas/tests
    copying mahotas/tests/test_gvoronoi.py -> build/lib.linux-x86_64-3.8/mahotas/tests
    copying mahotas/tests/test_template_match.py -> build/lib.linux-x86_64-3.8/mahotas/tests
    copying mahotas/tests/test_convolve.py -> build/lib.linux-x86_64-3.8/mahotas/tests
    copying mahotas/tests/test_polygon.py -> build/lib.linux-x86_64-3.8/mahotas/tests
    copying mahotas/tests/test_find.py -> build/lib.linux-x86_64-3.8/mahotas/tests
    copying mahotas/tests/test_median_filter.py -> build/lib.linux-x86_64-3.8/mahotas/tests
    copying mahotas/tests/test_dilate_erode.py -> build/lib.linux-x86_64-3.8/mahotas/tests
    copying mahotas/tests/test_moments.py -> build/lib.linux-x86_64-3.8/mahotas/tests
    copying mahotas/tests/test_center_of_mass.py -> build/lib.linux-x86_64-3.8/mahotas/tests
    copying mahotas/tests/test_mean_filter.py -> build/lib.linux-x86_64-3.8/mahotas/tests
    copying mahotas/tests/utils.py -> build/lib.linux-x86_64-3.8/mahotas/tests
    copying mahotas/tests/test_labeled.py -> build/lib.linux-x86_64-3.8/mahotas/tests
    copying mahotas/tests/test_edge.py -> build/lib.linux-x86_64-3.8/mahotas/tests
    creating build/lib.linux-x86_64-3.8/mahotas/demos/data
    copying mahotas/demos/data/nuclear.png -> build/lib.linux-x86_64-3.8/mahotas/demos/data
    copying mahotas/demos/data/luispedro.jpg -> build/lib.linux-x86_64-3.8/mahotas/demos/data
    copying mahotas/demos/data/lena.jpg -> build/lib.linux-x86_64-3.8/mahotas/demos/data
    copying mahotas/demos/data/DepartmentStore.jpg -> build/lib.linux-x86_64-3.8/mahotas/demos/data
    creating build/lib.linux-x86_64-3.8/mahotas/tests/data
    copying mahotas/tests/data/1bpp.bmp -> build/lib.linux-x86_64-3.8/mahotas/tests/data
    copying mahotas/tests/data/rgba.png -> build/lib.linux-x86_64-3.8/mahotas/tests/data
    copying mahotas/tests/data/luispedro.npy -> build/lib.linux-x86_64-3.8/mahotas/tests/data
    copying mahotas/tests/data/determinant_zero.png -> build/lib.linux-x86_64-3.8/mahotas/tests/data
    running build_ext
    building 'mahotas._bbox' extension
    creating build/temp.linux-x86_64-3.8
    creating build/temp.linux-x86_64-3.8/mahotas
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -DPY_ARRAY_UNIQUE_SYMBOL=Mahotas_PyArray_API_Symbol -I[] -I/home/inada-n/pypi-ansi/.venv/include -I/home/inada-n/pyenv/versions/3.8.1/include/python3.8 -c mahotas/_bbox.cpp -o build/temp.linux-x86_64-3.8/mahotas/_bbox.o
    In file included from mahotas/numpypp/array.hpp:17,
                     from mahotas/_bbox.cpp:11:
    mahotas/numpypp/numpy.hpp:11:10: fatal error: numpy/ndarrayobject.h: No such file or directory
       11 | #include <numpy/ndarrayobject.h>
          |          ^~~~~~~~~~~~~~~~~~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/inada-n/pypi-ansi/.venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-3g99mel1/mahotas/setup.py'"'"'; __file__='"'"'/tmp/pip-install-3g99mel1/mahotas/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-_zgrddju/install-record.txt --single-version-externally-managed --compile --install-headers /home/inada-n/pypi-ansi/.venv/include/site/python3.8/mahotas Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


Trying stackprinter ... ok
Trying trafaret ... ok
Trying wsgi-request-logger ... ok
Trying pytorch-transformers ... ok
Trying parsley ... ok
Trying concurrentloghandler ... ok
Trying anytree ... ok
Trying eth-hash ... ok
Trying splinter ... ok
Trying pygetwindow ... ok
Trying pylama ... ok
Trying sphinx-autobuild ... ok
Trying pip-licenses ... failed
Output:     ERROR: Command errored out with exit status 1:
     command: /home/inada-n/pypi-ansi/.venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-gl1e50mf/pip-licenses/setup.py'"'"'; __file__='"'"'/tmp/pip-install-gl1e50mf/pip-licenses/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-gl1e50mf/pip-licenses/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-gl1e50mf/pip-licenses/setup.py", line 34, in <module>
        from piplicenses import (__pkgname__ as PKG_NAME, __version__ as VERSION,
      File "/tmp/pip-install-gl1e50mf/pip-licenses/piplicenses.py", line 42, in <module>
        from prettytable import PrettyTable
    ModuleNotFoundError: No module named 'prettytable'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


Trying draftjs-exporter ... ok
Trying tifffile ... ok
Trying injector ... ok
Trying halo ... ok
Trying textdistance ... ok
Trying auth0-python ... ok
Trying pem ... timedout
Trying requests-html ... ok
Trying pyarabic ... ok
Trying yappi ... ok
Trying property-manager ... ok
Trying django-mathfilters ... ok
Trying pymc3 ... ok
Trying cybox ... ok
Trying confuse ... ok
Trying algoliasearch ... ok
Trying eth-account ... ok
Trying hexbytes ... ok
Trying xdg ... failed
Output:   ERROR: Command errored out with exit status 1:
   command: /home/inada-n/pypi-ansi/.venv/bin/python3 /home/inada-n/pypi-ansi/.venv/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-qexkbefd/overlay --no-warn-script-location --no-binary :all: --only-binary :none: -i https://pypi.org/simple -- 'poetry>=0.12'
       cwd: None
  Complete output (50 lines):
  Collecting poetry>=0.12
    Using cached https://files.pythonhosted.org/packages/eb/98/a598bb2663e0e43557a99a243ebd21b27b1fc07d2c146b2554aa45ace5dc/poetry-1.0.3.tar.gz
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /home/inada-n/pypi-ansi/.venv/bin/python3 /home/inada-n/pypi-ansi/.venv/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpkl86snwh
         cwd: /tmp/pip-install-v4vfauex/poetry
    Complete output (36 lines):
    Traceback (most recent call last):
      File "/home/inada-n/pypi-ansi/.venv/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>
        main()
      File "/home/inada-n/pypi-ansi/.venv/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 197, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/home/inada-n/pypi-ansi/.venv/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 54, in get_requires_for_build_wheel
        return hook(config_settings)
      File "/tmp/pip-build-env-n78wtq66/overlay/lib/python3.8/site-packages/intreehooks.py", line 53, in get_requires_for_build_wheel
        return self._backend.get_requires_for_build_sdist(config_settings)
      File "/tmp/pip-build-env-n78wtq66/overlay/lib/python3.8/site-packages/intreehooks.py", line 38, in _backend
        obj = self._module_from_dir(modname)
      File "/tmp/pip-build-env-n78wtq66/overlay/lib/python3.8/site-packages/intreehooks.py", line 25, in _module_from_dir
        mod = importlib.import_module(modname)
      File "/home/inada-n/pyenv/versions/3.8.1/lib/python3.8/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
      File "<frozen importlib._bootstrap>", line 991, in _find_and_load
      File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
      File "<frozen importlib._bootstrap>", line 991, in _find_and_load
      File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 783, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/tmp/pip-install-v4vfauex/poetry/poetry/masonry/__init__.py", line 10, in <module>
        from .builder import Builder
      File "/tmp/pip-install-v4vfauex/poetry/poetry/masonry/builder.py", line 1, in <module>
        from .builders.complete import CompleteBuilder
      File "/tmp/pip-install-v4vfauex/poetry/poetry/masonry/builders/__init__.py", line 1, in <module>
        from .complete import CompleteBuilder
      File "/tmp/pip-install-v4vfauex/poetry/poetry/masonry/builders/complete.py", line 6, in <module>
        from poetry.factory import Factory
      File "/tmp/pip-install-v4vfauex/poetry/poetry/factory.py", line 10, in <module>
        from clikit.api.io.io import IO
    ModuleNotFoundError: No module named 'clikit'
    ----------------------------------------
  ERROR: Command errored out with exit status 1: /home/inada-n/pypi-ansi/.venv/bin/python3 /home/inada-n/pypi-ansi/.venv/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpkl86snwh Check the logs for full command output.
  WARNING: You are using pip version 19.2.3, however version 20.0.2 is available.
  You should consider upgrading via the 'pip install --upgrade pip' command.
  ----------------------------------------
ERROR: Command errored out with exit status 1: /home/inada-n/pypi-ansi/.venv/bin/python3 /home/inada-n/pypi-ansi/.venv/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-qexkbefd/overlay --no-warn-script-location --no-binary :all: --only-binary :none: -i https://pypi.org/simple -- 'poetry>=0.12' Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


Trying html ... failed
Output:     ERROR: Command errored out with exit status 1:
     command: /home/inada-n/pypi-ansi/.venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-b0w1fwom/html/setup.py'"'"'; __file__='"'"'/tmp/pip-install-b0w1fwom/html/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-b0w1fwom/html/
    Complete output (17 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/inada-n/pypi-ansi/.venv/lib/python3.8/site-packages/setuptools/__init__.py", line 20, in <module>
        from setuptools.dist import Distribution, Feature
      File "/home/inada-n/pypi-ansi/.venv/lib/python3.8/site-packages/setuptools/dist.py", line 34, in <module>
        from setuptools.depends import Require
      File "/home/inada-n/pypi-ansi/.venv/lib/python3.8/site-packages/setuptools/depends.py", line 7, in <module>
        from .py33compat import Bytecode
      File "/home/inada-n/pypi-ansi/.venv/lib/python3.8/site-packages/setuptools/py33compat.py", line 11, in <module>
        from setuptools.extern.six.moves import html_parser
      File "/home/inada-n/pypi-ansi/.venv/lib/python3.8/site-packages/setuptools/_vendor/six.py", line 92, in __get__
        result = self._resolve()
      File "/home/inada-n/pypi-ansi/.venv/lib/python3.8/site-packages/setuptools/_vendor/six.py", line 115, in _resolve
        return _import_module(self.mod)
      File "/home/inada-n/pypi-ansi/.venv/lib/python3.8/site-packages/setuptools/_vendor/six.py", line 82, in _import_module
        __import__(name)
    ModuleNotFoundError: No module named 'html.parser'; 'html' is not a package
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


Trying eth-rlp ... ok
Trying nose-progressive ... ok
Trying dataproperty ... ok
Trying kappa ... ok
Trying inquirer ... ok
Trying mbstrdecoder ... ok
Trying django-compat ... ok
Trying pyspark-stubs ... ok
Trying click-spinner ... ok
Trying static3 ... ok
Trying zappa ... ok
Trying pytest-factoryboy ... ok
Trying cos-python-sdk-v5 ... ok
Trying flake8-string-format ... ok
Trying wagtail ... ok
Trying deap ... ok
Trying python-twitter ... ok
Trying awesome-slugify ... ok
Trying eeweather ... ok
Trying exchangelib ... ok
Trying pep517 ... timedout
Trying django-jet ... ok
Trying pypika ... ok
Trying pyroma ... ok
Trying edx-organizations ... ok
Trying django-watchman ... ok
Trying requests-async ... ok
Trying opentracing-instrumentation ... ok
Trying multiaddr ... ok
Trying keyboard ... ok
Trying lzstring ... ok
Trying bok-choy ... ok
Trying pilkit ... ok
Trying turicreate ... failed
Output:     ERROR: Command errored out with exit status 1:
     command: /home/inada-n/pypi-ansi/.venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-a6lecaj1/turicreate/setup.py'"'"'; __file__='"'"'/tmp/pip-install-a6lecaj1/turicreate/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-t6sg7uir/install-record.txt --single-version-externally-managed --compile --install-headers /home/inada-n/pypi-ansi/.venv/include/site/python3.8/turicreate
         cwd: /tmp/pip-install-a6lecaj1/turicreate/
    Complete output (28 lines):
    running install
    
    
    
            ==================================================================================
            TURICREATE ERROR
    
            If you see this message, pip install did not find an available binary package
            for your system.
    
            Supported Platforms:
                * macOS 10.12+ x86_64.
                * Linux x86_64 (including WSL on Windows 10).
    
            Support Python Versions:
                * 2.7
                * 3.5
                * 3.6
                * 3.7
    
    
            Another possible cause of this error is an outdated pip version. Try:
                `pip install -U pip`
    
            ==================================================================================
    
    
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/inada-n/pypi-ansi/.venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-a6lecaj1/turicreate/setup.py'"'"'; __file__='"'"'/tmp/pip-install-a6lecaj1/turicreate/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-t6sg7uir/install-record.txt --single-version-externally-managed --compile --install-headers /home/inada-n/pypi-ansi/.venv/include/site/python3.8/turicreate Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


Trying edx-completion ... ok
Trying ratelimiter ... ok
Trying graphyte ... ok
Trying gtts ... timedout
Trying ipfshttpclient ... timedout
Trying pytest-bdd ... ok
Trying pprintpp ... ok
Trying django-log-request-id ... ok
Trying django-imagekit ... ok
Trying py-mini-racer ... timedout
Trying oci ... ok
Trying aiostream ... ok
Trying janome ... timedout
Trying qtpy ... ok
Trying dacite ... ok
Trying ocspresponder ... failed
Output:     ERROR: Command errored out with exit status 1:
     command: /home/inada-n/pypi-ansi/.venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-wlajnas9/ocspresponder/setup.py'"'"'; __file__='"'"'/tmp/pip-install-wlajnas9/ocspresponder/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-wlajnas9/ocspresponder/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-wlajnas9/ocspresponder/setup.py", line 8, in <module>
        with open(path.join(here, 'README.md'), encoding='utf-8') as f:
      File "/home/inada-n/pyenv/versions/3.8.1/lib/python3.8/codecs.py", line 905, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-wlajnas9/ocspresponder/README.md'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


Trying vadersentiment ... ok
Trying mixer ... ok
Trying faulthandler ... failed
Output:     ERROR: Command errored out with exit status 1:
     command: /home/inada-n/pypi-ansi/.venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ttfrt34h/faulthandler/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ttfrt34h/faulthandler/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-ttfrt34h/faulthandler/
    Complete output (1 lines):
    ERROR: faulthandler is a builtin module since Python 3.3
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


Trying kivy ... timedout
Trying tflearn ... ok
Trying aioopenssl ... ok
Trying freetype-py ... ok
Trying pytd ... ok
Trying bump2version ... ok
Trying pybase62 ... ok
Trying aiosasl ... ok
Trying unicode-slugify ... ok
Trying sqlitedict ... ok
Trying telethon ... ok
Trying delegator-py ... ok
Trying jsii ... ok
Trying featuretools ... ok
Trying win-unicode-console ... ok
Trying httpx ... ok
Trying aioxmpp ... ok
Trying pycld2 ... timedout
Trying sudachipy ... ok
Trying gcovr ... ok
Trying publication ... timedout
Trying colorful ... ok
Trying yamale ... ok
Trying pytablewriter ... ok
Trying requests-credssp ... ok
Trying dbt ... ok
Trying lazy-import ... ok
Trying django-redshift-backend ... ok
Trying times ... ok
Trying flask-mongoengine ... timedout
Trying django-webtest ... ok
Trying spyder ... ok
Trying salesforce-fuelsdk ... ok
Trying spyne ... ok
Trying niet ... ok
Trying flake8-mypy ... ok
Trying pytrends ... ok
Trying pytelegrambotapi ... ok
Trying lomond ... ok
Trying py2-ipaddress ... failed
Output:     ERROR: Command errored out with exit status 1:
     command: /home/inada-n/pypi-ansi/.venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-wsfl__g0/py2-ipaddress/setup.py'"'"'; __file__='"'"'/tmp/pip-install-wsfl__g0/py2-ipaddress/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-wsfl__g0/py2-ipaddress/
    Complete output (1 lines):
    py2-ipaddress: For Python 3.x, please use the official ipaddress module.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


Trying parquet ... ok
Trying flake8-future-import ... ok
Trying line-bot-sdk ... ok
Trying yarn-api-client ... ok
Trying conllu ... ok
Trying glean-parser ... ok
Trying you-get ... ok
Trying vistir ... ok
Trying pyjq ... timedout
Trying google-endpoints-api-management ... ok
Trying py-vapid ... ok
Trying python2-pythondialog ... failed
Output:     ERROR: Command errored out with exit status 1:
     command: /home/inada-n/pypi-ansi/.venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-j9bgwp51/python2-pythondialog/setup.py'"'"'; __file__='"'"'/tmp/pip-install-j9bgwp51/python2-pythondialog/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-j9bgwp51/python2-pythondialog/
    Complete output (8 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-j9bgwp51/python2-pythondialog/setup.py", line 32, in <module>
        from dialog import __version__ as VERSION
      File "/tmp/pip-install-j9bgwp51/python2-pythondialog/dialog.py", line 264
        except OSError, e:
                      ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


Trying pytype ... ok
Trying ccxt ... ok
Trying rouge ... ok
Trying aws-cdk-aws-ec2 ... ok
Trying natto-py ... ok
Trying certipy ... ok
Trying pyrogram ... ok
Trying pyinstrument ... failed
Output:     ERROR: Command errored out with exit status 1:
     command: /home/inada-n/pypi-ansi/.venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-54hy_0xw/pyinstrument/setup.py'"'"'; __file__='"'"'/tmp/pip-install-54hy_0xw/pyinstrument/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-t3jq0bo6/install-record.txt --single-version-externally-managed --compile --install-headers /home/inada-n/pypi-ansi/.venv/include/site/python3.8/pyinstrument
         cwd: /tmp/pip-install-54hy_0xw/pyinstrument/
    Complete output (4 lines):
    running install
    running build
    running build_py
    error: [Errno 2] No such file or directory: 'npm'
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/inada-n/pypi-ansi/.venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-54hy_0xw/pyinstrument/setup.py'"'"'; __file__='"'"'/tmp/pip-install-54hy_0xw/pyinstrument/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-t3jq0bo6/install-record.txt --single-version-externally-managed --compile --install-headers /home/inada-n/pypi-ansi/.venv/include/site/python3.8/pyinstrument Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


Trying pyhdb ... ok
Trying characteristic ... ok
Trying requirementslib ... timedout
Trying pyscss ... ok
Trying django-cleanup ... ok
Trying lupa ... timedout
Trying python-statemachine ... ok
Trying ushlex ... ok
Trying inject ... ok
Trying executor ... ok
Trying pyct ... failed
Output:     ERROR: Command errored out with exit status 1:
     command: /home/inada-n/pypi-ansi/.venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ol3tirhh/pyct/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ol3tirhh/pyct/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-ol3tirhh/pyct/
    Complete output (32 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ol3tirhh/pyct/setup.py", line 7, in <module>
        setup()
      File "/home/inada-n/pypi-ansi/.venv/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/home/inada-n/pyenv/versions/3.8.1/lib/python3.8/distutils/core.py", line 121, in setup
        dist.parse_config_files()
      File "/home/inada-n/pypi-ansi/.venv/lib/python3.8/site-packages/setuptools/dist.py", line 699, in parse_config_files
        parse_configuration(self, self.command_options,
      File "/home/inada-n/pypi-ansi/.venv/lib/python3.8/site-packages/setuptools/config.py", line 120, in parse_configuration
        meta.parse()
      File "/home/inada-n/pypi-ansi/.venv/lib/python3.8/site-packages/setuptools/config.py", line 425, in parse
        section_parser_method(section_options)
      File "/home/inada-n/pypi-ansi/.venv/lib/python3.8/site-packages/setuptools/config.py", line 398, in parse_section
        self[name] = value
      File "/home/inada-n/pypi-ansi/.venv/lib/python3.8/site-packages/setuptools/config.py", line 183, in __setitem__
        value = parser(value)
      File "/home/inada-n/pypi-ansi/.venv/lib/python3.8/site-packages/setuptools/config.py", line 513, in _parse_version
        version = self._parse_attr(value, self.package_dir)
      File "/home/inada-n/pypi-ansi/.venv/lib/python3.8/site-packages/setuptools/config.py", line 348, in _parse_attr
        module = import_module(module_name)
      File "/home/inada-n/pyenv/versions/3.8.1/lib/python3.8/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
      File "<frozen importlib._bootstrap>", line 991, in _find_and_load
      File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
      File "<frozen importlib._bootstrap>", line 991, in _find_and_load
      File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'param'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


Trying inflector ... ok
Trying ariadne ... ok
Trying django-sortedm2m ... ok
Trying benchexec ... timedout
Trying qtawesome ... ok
Trying hexdump ... ok
Trying questionary ... timedout
Trying gender-guesser ... ok
Trying doc-warden ... ok
Trying aws-cdk-aws-applicationautoscaling ... timedout
Trying pretrainedmodels ... ok
Trying art ... ok
Trying proxy-py ... ok
Trying uproot ... ok
Trying tslearn ... failed
Output:     ERROR: Command errored out with exit status 1:
     command: /home/inada-n/pypi-ansi/.venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-yvj38dgw/tslearn/setup.py'"'"'; __file__='"'"'/tmp/pip-install-yvj38dgw/tslearn/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-yvj38dgw/tslearn/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-yvj38dgw/tslearn/setup.py", line 3, in <module>
        import numpy
    ModuleNotFoundError: No module named 'numpy'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


Trying talon ... ok
Trying maya ... ok
Trying dash-bootstrap-components ... ok
Trying pytest-splinter ... ok
Trying polyglot ... ok
Trying newspaper3k ... ok
Trying dvc ... timedout
Trying nbval ... ok
Trying pythondialog ... ok
Trying pyvisa ... ok
Trying rstcheck ... ok
Trying flake8-broken-line ... timedout
Trying albumentations ... ok
Trying django-pandas ... ok
Trying gino ... ok
Trying kmodes ... ok
Trying oic ... ok
Trying django-admin-sortable ... ok
Trying oci-cli ... timedout
Trying proxmoxer ... ok
Trying azure-cli-profile ... ok
Trying django-ratelimit-backend ... ok
Trying twitter ... ok
Trying python-logstash-async ... timedout
Trying flexmock ... ok
Trying jsons ... ok
Trying django-babel ... ok
Trying pytest-allure-adaptor ... ok
Trying django-render-block ... failed
Output:   ERROR: Could not find a version that satisfies the requirement django-render-block (from versions: none)
ERROR: No matching distribution found for django-render-block
WARNING: You are using pip version 19.2.3, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


Trying goslate ... ok
Trying robotframework-pageobjectlibrary ... ok
Trying ics ... ok
Trying logdna ... ok
Trying seleniumbase ... ok
Trying sceptre ... ok
Trying mail-parser ... ok
Trying aws-cdk-aws-autoscaling ... timedout
Trying rethinkdb ... failed
Output:     ERROR: Command errored out with exit status 1:
     command: /home/inada-n/pypi-ansi/.venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-tgrcv7l5/rethinkdb/setup.py'"'"'; __file__='"'"'/tmp/pip-install-tgrcv7l5/rethinkdb/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-tgrcv7l5/rethinkdb/
    Complete output (13 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-tgrcv7l5/rethinkdb/setup.py", line 30, in <module>
        from rethinkdb.version import VERSION
      File "/tmp/pip-install-tgrcv7l5/rethinkdb/rethinkdb/__init__.py", line 88, in <module>
        r = RethinkDB()
      File "/tmp/pip-install-tgrcv7l5/rethinkdb/rethinkdb/__init__.py", line 36, in __init__
        from rethinkdb import (
      File "/tmp/pip-install-tgrcv7l5/rethinkdb/rethinkdb/_dump.py", line 35, in <module>
        from rethinkdb import _export, utils_common
      File "/tmp/pip-install-tgrcv7l5/rethinkdb/rethinkdb/_export.py", line 38, in <module>
        import six
    ModuleNotFoundError: No module named 'six'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


Trying scikit-plot ... ok
Trying gluonnlp ... ok
Trying tinysegmenter ... ok
Trying socketio-client ... ok
Trying sops ... ok
Trying nameko ... ok
Trying powerline-status ... ok
Trying jaconv ... ok
Trying beaver ... ok
Trying pgeocode ... ok
Trying django-url-filter ... ok
Trying pymongocrypt ... ok
Trying rasa ... timedout
Trying irc ... timedout
Trying django-js-reverse ... ok
Trying office365-rest-python-client ... ok
Trying pyemd ... timedout
Trying pyupgrade ... ok
Trying django-prettyjson ... ok
Trying softlayer ... ok
Trying pikepdf ... timedout
Trying pysimplegui ... ok
Trying transliterate ... ok
Trying yfinance ... ok
Trying pytest-testconfig ... ok
Trying publicsuffixlist ... ok
Trying eliot ... ok
Trying http-parser ... failed
Output:     ERROR: Command errored out with exit status 1:
     command: /home/inada-n/pypi-ansi/.venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-iz379kc1/http-parser/setup.py'"'"'; __file__='"'"'/tmp/pip-install-iz379kc1/http-parser/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-59ix8pqz/install-record.txt --single-version-externally-managed --compile --install-headers /home/inada-n/pypi-ansi/.venv/include/site/python3.8/http-parser
         cwd: /tmp/pip-install-iz379kc1/http-parser/
    Complete output (82 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.8
    creating build/lib.linux-x86_64-3.8/http_parser
    copying http_parser/_socketio.py -> build/lib.linux-x86_64-3.8/http_parser
    copying http_parser/http.py -> build/lib.linux-x86_64-3.8/http_parser
    copying http_parser/__init__.py -> build/lib.linux-x86_64-3.8/http_parser
    copying http_parser/pyparser.py -> build/lib.linux-x86_64-3.8/http_parser
    copying http_parser/util.py -> build/lib.linux-x86_64-3.8/http_parser
    copying http_parser/reader.py -> build/lib.linux-x86_64-3.8/http_parser
    running build_ext
    building 'http_parser.parser' extension
    creating build/temp.linux-x86_64-3.8
    creating build/temp.linux-x86_64-3.8/http_parser
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Iparser -I/home/inada-n/pypi-ansi/.venv/include -I/home/inada-n/pyenv/versions/3.8.1/include/python3.8 -c http_parser/http_parser.c -o build/temp.linux-x86_64-3.8/http_parser/http_parser.o
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Iparser -I/home/inada-n/pypi-ansi/.venv/include -I/home/inada-n/pyenv/versions/3.8.1/include/python3.8 -c http_parser/parser.c -o build/temp.linux-x86_64-3.8/http_parser/parser.o
    http_parser/parser.c: In function '__Pyx_GetException':
    http_parser/parser.c:6249:24: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_type'; did you mean 'curexc_type'?
     6249 |     tmp_type = tstate->exc_type;
          |                        ^~~~~~~~
          |                        curexc_type
    http_parser/parser.c:6250:25: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_value'; did you mean 'curexc_value'?
     6250 |     tmp_value = tstate->exc_value;
          |                         ^~~~~~~~~
          |                         curexc_value
    http_parser/parser.c:6251:22: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_traceback'; did you mean 'curexc_traceback'?
     6251 |     tmp_tb = tstate->exc_traceback;
          |                      ^~~~~~~~~~~~~
          |                      curexc_traceback
    http_parser/parser.c:6252:13: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_type'; did you mean 'curexc_type'?
     6252 |     tstate->exc_type = local_type;
          |             ^~~~~~~~
          |             curexc_type
    http_parser/parser.c:6253:13: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_value'; did you mean 'curexc_value'?
     6253 |     tstate->exc_value = local_value;
          |             ^~~~~~~~~
          |             curexc_value
    http_parser/parser.c:6254:13: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_traceback'; did you mean 'curexc_traceback'?
     6254 |     tstate->exc_traceback = local_tb;
          |             ^~~~~~~~~~~~~
          |             curexc_traceback
    http_parser/parser.c: In function '__Pyx_ExceptionSave':
    http_parser/parser.c:7460:21: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_type'; did you mean 'curexc_type'?
     7460 |     *type = tstate->exc_type;
          |                     ^~~~~~~~
          |                     curexc_type
    http_parser/parser.c:7461:22: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_value'; did you mean 'curexc_value'?
     7461 |     *value = tstate->exc_value;
          |                      ^~~~~~~~~
          |                      curexc_value
    http_parser/parser.c:7462:19: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_traceback'; did you mean 'curexc_traceback'?
     7462 |     *tb = tstate->exc_traceback;
          |                   ^~~~~~~~~~~~~
          |                   curexc_traceback
    http_parser/parser.c: In function '__Pyx_ExceptionReset':
    http_parser/parser.c:7474:24: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_type'; did you mean 'curexc_type'?
     7474 |     tmp_type = tstate->exc_type;
          |                        ^~~~~~~~
          |                        curexc_type
    http_parser/parser.c:7475:25: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_value'; did you mean 'curexc_value'?
     7475 |     tmp_value = tstate->exc_value;
          |                         ^~~~~~~~~
          |                         curexc_value
    http_parser/parser.c:7476:22: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_traceback'; did you mean 'curexc_traceback'?
     7476 |     tmp_tb = tstate->exc_traceback;
          |                      ^~~~~~~~~~~~~
          |                      curexc_traceback
    http_parser/parser.c:7477:13: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_type'; did you mean 'curexc_type'?
     7477 |     tstate->exc_type = type;
          |             ^~~~~~~~
          |             curexc_type
    http_parser/parser.c:7478:13: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_value'; did you mean 'curexc_value'?
     7478 |     tstate->exc_value = value;
          |             ^~~~~~~~~
          |             curexc_value
    http_parser/parser.c:7479:13: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_traceback'; did you mean 'curexc_traceback'?
     7479 |     tstate->exc_traceback = tb;
          |             ^~~~~~~~~~~~~
          |             curexc_traceback
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/inada-n/pypi-ansi/.venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-iz379kc1/http-parser/setup.py'"'"'; __file__='"'"'/tmp/pip-install-iz379kc1/http-parser/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-59ix8pqz/install-record.txt --single-version-externally-managed --compile --install-headers /home/inada-n/pypi-ansi/.venv/include/site/python3.8/http-parser Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


Trying publicsuffix2 ... ok
Trying profitbricks ... ok
Trying grapheme ... ok
Trying bagit ... ok
Trying manhole ... ok
Trying django-leaflet ... ok
Trying mdv ... ok
